# -*- mode: ruby -*-
# # vi: set ft=ruby :
# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version '>= 1.6.0'
VAGRANTFILE_API_VERSION = '2'.freeze
# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('servers.yaml')
# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Iterate through entries in YAML file
  servers.each do |server|
    config.vm.define server['name'] do |srv|
      srv.vm.box = server['box']
      srv.vm.synced_folder '../', '/sourcegraph', type: "rsync", rsync__args: ["--verbose", "--archive", "--delete", "-z"]
      srv.vm.boot_timeout = 600

      # Setup for CI or Local
      case ENV['VAGRANT_RUN_ENV']
      when 'CI'
        project_id = server['project_id']
        external_ip = server['external_ip']
        use_private_ip = server['use_private_ip']
        username = server['username']
        ssh_key_path = server['ssh_key_path']
      else
        project_id = ENV['VAGRANT_GCP_PROJECT_ID'] || 'sourcegraph-server'
        external_ip = nil
        use_private_ip = false
        username = ENV['VAGRANT_SSH_USER'] || ENV['USER']
        ssh_key_path = ENV['VAGRANT_SSH_KEY'] || '~/.ssh/id_rsa'
      end

      srv.vm.provider :google do |g, o|
        g.machine_type = server['machine_type']
        g.image = 'e2e-d6b5231e-2020-09-15t14-08-26z'
        g.image_project_id = 'sourcegraph-ci'
        g.google_project_id = project_id
        g.name = "#{server['name']}-"+"#{Time.now.to_i}"
        g.network = server['network']
        g.external_ip = external_ip
        g.use_private_ip = use_private_ip
        g.disk_size = 20
        o.ssh.username = username
        o.ssh.private_key_path = ssh_key_path
      end

      srv.vm.provision 'shell', inline: <<-SHELL
        #!/usr/bin/env bash
# Go
sudo add-apt-repository ppa:longsleep/golang
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.listbackports

        apt-get update
        apt-get install -y --no-install-recommends jq
        # build-essential \
        # curl \
        # libbz2-dev \
        # libffi-dev \
        # liblzma-dev \
        # libncurses5-dev \
        # libncursesw5-dev \
        # libreadline-dev \
        # libsqlite3-dev \
        # libssl-dev \
        # llvm \
        # make \
        # python-openssl \
        # tk-dev \
        # wget \
        # xz-utils \
        # libpcre3-dev pkg-config musl-tools \
        # golang-go \
        # zlib1g-dev && \
        curl -o /root/go.tar.gz -L https://golang.org/dl/go1.15.2.linux-amd64.tar.gz
        tar -C /usr/local -xzf /root/go.tar.gz
        echo "export PATH=$PATH:/usr/local/go/bin" >> /root/.profile
        ssh-keyscan -H github.com >> /root/.ssh/known_hosts
        NVM_VERSION="$(curl https://api.github.com/repos/nvm-sh/nvm/releases/latest | jq -r .name)"
        curl -L https://raw.githubusercontent.com/nvm-sh/nvm/"$NVM_VERSION"/install.sh | sh
      SHELL

      server['shell_commands'].each do |sh|
        srv.vm.provision 'shell', inline: sh
      end
    end
  end
end
